language: cpp
notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc
      env: LIBTOOLFLAGS="--mode=link"
    - os: linux
      compiler: clang
      env: LIBTOOLFLAGS="--mode=link"
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - gcc-5
    - g++-5
    - clang-3.8

osx_image: xcode7.3

install:
  - if [ "$CC" = "gcc" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CC" = "clang" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi

script: ./script/cibuild
