language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   - llvm-toolchain-precise-3.8
   packages:
   - gcc-5
   - g++-5
   - clang-3.8

script: make && make check

osx_image: xcode7.3
notifications:
  email: false
