language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

addons:
 apt:
   packages:
   - gcc-5
   - g++-5
   - clang-3.9

script: make && make check

osx_image: xcode7.3
notifications:
  email: false
